// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PocketMonster.Data.ContextDB;

namespace PocketMonster.Data.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20210914202451_tabelaInicial")]
    partial class tabelaInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PocketMonster.Model.Entities.Ginasio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("GymLiderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GymTipo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GymLiderId");

                    b.ToTable("Ginasios");
                });

            modelBuilder.Entity("PocketMonster.Model.Entities.Pokemon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegistroPokedex")
                        .HasColumnType("int");

                    b.Property<string>("Tipo1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo2")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pokemon");
                });

            modelBuilder.Entity("PocketMonster.Model.Entities.PokemonTreinador", b =>
                {
                    b.Property<Guid>("IdPokemon")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdTreinador")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdPokemon", "IdTreinador");

                    b.HasIndex("IdTreinador");

                    b.ToTable("PokemonTreinadores");
                });

            modelBuilder.Entity("PocketMonster.Model.Entities.Treinador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Treinadores");
                });

            modelBuilder.Entity("PocketMonster.Model.Entities.Ginasio", b =>
                {
                    b.HasOne("PocketMonster.Model.Entities.Treinador", "GymLider")
                        .WithMany()
                        .HasForeignKey("GymLiderId");

                    b.Navigation("GymLider");
                });

            modelBuilder.Entity("PocketMonster.Model.Entities.PokemonTreinador", b =>
                {
                    b.HasOne("PocketMonster.Model.Entities.Pokemon", "Pokemon")
                        .WithMany("PokemonTreinador")
                        .HasForeignKey("IdPokemon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PocketMonster.Model.Entities.Treinador", "Treinador")
                        .WithMany("PokemonCapturados")
                        .HasForeignKey("IdTreinador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pokemon");

                    b.Navigation("Treinador");
                });

            modelBuilder.Entity("PocketMonster.Model.Entities.Pokemon", b =>
                {
                    b.Navigation("PokemonTreinador");
                });

            modelBuilder.Entity("PocketMonster.Model.Entities.Treinador", b =>
                {
                    b.Navigation("PokemonCapturados");
                });
#pragma warning restore 612, 618
        }
    }
}
